function RGGI2NYCA2019 = importRGGI2NYCA(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  RGGI2NYCA2019 = IMPORTFILE(FILE) reads data from the first worksheet
%  in the Microsoft Excel spreadsheet file named FILE.  Returns the data
%  as a table.
%
%  RGGI2NYCA2019 = IMPORTFILE(FILE, SHEET) reads from the specified
%  worksheet.
%
%  RGGI2NYCA2019 = IMPORTFILE(FILE, SHEET, DATALINES) reads from the
%  specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  RGGI2NYCA2019 = importfile("D:\EERL\EPA_AMPD\RGGI_2_NYCA_2019.xlsx", "Sheet1", [2, 184]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Sep-2020 21:33:56

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 184];
end

%% Setup the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 15);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":O" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["NYISOname", "PTID", "FacilityName", "FacilityID", "UnitID", "NYAMUnit", "Region", "UnitType", "FuelType", "OperatingTime", "GrossLoadMWh", "NamePlateRatingMW", "NetEnergyGWh", "FacilityLatitude", "FacilityLongitude"];
opts.VariableTypes = ["categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["NYISOname", "FacilityName", "UnitID", "NYAMUnit", "Region", "UnitType", "FuelType"], "EmptyFieldRule", "auto");
% Import the data
RGGI2NYCA2019 = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":O" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    RGGI2NYCA2019 = [RGGI2NYCA2019; tb]; %#ok<AGROW>
end

end