function RE_inprof_vis(YMatrix1, VRE)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 13-Mar-2019 16:00:56

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','GHI Gen Bus #53','Marker','diamond');
set(plot1(2),'DisplayName','GHI Gen Bus #54','Marker','diamond');
set(plot1(3),'DisplayName','NYC Gen Bus #55','Marker','v');
set(plot1(4),'DisplayName','NYC Gen Bus #56','Marker','v');
set(plot1(5),'DisplayName','NYC Gen Bus #57','Marker','v');
set(plot1(6),'DisplayName','LI Gen Bus #58','Marker','^');
set(plot1(7),'DisplayName','LI Gen Bus #59','Marker','^');
set(plot1(8),'DisplayName','GHI Gen Bus #60','Marker','diamond');
set(plot1(9),'DisplayName','NE Gen Bus #61','Marker','+');
set(plot1(10),'DisplayName','A2F Load Bus #63','Marker','square');
set(plot1(11),'DisplayName','A2F Gen Bus #64','Marker','square');
set(plot1(12),'DisplayName','A2F Gen Bus #65','Marker','square');
set(plot1(13),'DisplayName','A2F Gen Bus #66','Marker','square');
set(plot1(14),'DisplayName','A2F Gen Bus #67','Marker','square');
set(plot1(15),'DisplayName','A2F Gen Bus #68','Marker','square');

% Create ylabel
ylabel('Power Output (MW)');

% Create xlabel
xlabel('Time (hour)');

% Create title
titlestr = strcat(VRE,' Generation by Region');
title(titlestr);

% Uncomment the following line to preserve the X-limits of the axes
xlim(axes1,[0 24]);
box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Location','best');

hold(axes1,'off');

end

